n_discriminator: 5
n_detoxifier: 10
generation_steps: 100
log_result: 100
save_steps: 2000
save_model: True
dataset_path: civil_comments_subset
model_path: /Data/deeksha/disha/code_p/text-detoxification/model
disc_type: Multi-class
wandb_project: Text-Detoxification
wandb_run_name: run4
detoxifier_lr: 0.0001
discriminator_lr: 0.0001
batch_size: 8
detoxifier_weight_decay: 0.01
discriminator_weight_decay: 0.01
detoxifier_max_grad_norm: 5
discriminator_max_grad_norm: 5
detoxifier_step_size: 1
discriminator_step_size: 1
max_length: 64
min_length: 4
device: cuda
num_epochs: 2
delta: 0.001
debug: True
